### PR TITLE
Fixed a crash happened when accessing a nil property

### PR DESCRIPTION
**Pull request by shannoga**
Described the crash here - https://github.com/SocialbitGmbH/SwiftAddressBook/issues/2

Hope it helps, thanks

### CODE REVIEW

**Comment by albertbori** [comment]
I can confirm that @TAKeanice 's suggestion of adding `?` after the initializer does solve the crash. (I applied this in my own ABAddressBook code)

**Comment by TAKeanice** [comment]
So can you change the request that I can merge the correct solution, @shannoga ?

**Comment by TAKeanice** [comment]
manually fixed

**Comment by albertbori** [comment]
My apologies to @shannoga I've reproduced this issue in #18. Oddly enough, using `?` to implicitly unwrap causes the cast to choke on nil values (sometimes).

**Comment by TAKeanice** [comment]
My apologies, too. I´ve never encountered that an optimizer does such evil things...

**Comment by TAKeanice** [comment]
@shannoga merged manually one more time :)

**Pull request closed without merging**
