### PR TITLE
Required changes for Swift 2.0

### PR DESCRIPTION
**Pull request by cbot**
These are required changes to make the code compile with the Swift 2.0 compiler.

### CODE REVIEW

**Comment by TAKeanice** [comment]
As soon as https://github.com/travis-ci/travis-ci/issues/4055 is resolved and an XCode 7.0 image for travis is out, I´ll let the test run again, and if it does not fail, I´ll merge that, ok?
Could you do me a favor and update the .travis.yml file in your branch then, in order to perform the checks?

**Comment by kostiakoval** [comment]
- Make a new branch swift_2.0 
- Disable that branch for travis. add this to travis file
```
branches:
  except:
    - swift_2.0
```
after that just keep working on swift_2.0 branch I would love to contribute as well

**Comment by TAKeanice** [comment]
Alright, I will do what @kostiakoval suggested.

**Comment by TAKeanice** [comment]
Merged https://github.com/SocialbitGmbH/SwiftAddressBook/pull/58 instead

**Pull request closed without merging**
