### PR TITLE
Added support to wrap existing ABRecord that can be obtained from the…

### PR DESCRIPTION
**Pull request by almilli**
… AddressBookUI and allows you to use wrapper objects.  Also added a recordType getter to the record object.

### CODE REVIEW

**Comment by TAKeanice** [comment]
For the function to create `SwiftAddressBookRecord`s from `ABRecord`s: Why not use the initializer directly?
Secondly, if the type of an ABRecord is really relevant to a user, I would like to lift the bare Int into a Swift enum, since it supports Swifts compile time checks!
Maybe the best solution for this would be to change the Initializer of `SwiftAddressBookRecord` to initialize a person, group or source as appropriate, because there is no such thing as a bare `ABRecord`. The convert functions would only need to safely cast to the correct type afterwards.

**Comment by almilli** [comment]
You can't use the initializer directly because it's not public.  It was giving me a compile error when I tried that.  Same goes for the other similar wrapper classes.  The problem I ran into is that I am using the ABPeoplePickerNavigationController user interface for contacts and it gives out ABRecordRef (which is just an alias for ABRecord).  And it was impossible to use the SwiftAddressBook convenience classes with the returned results if it was a record with a recordId of -1 (unsaved record).  When it is an unsaved record it's impossible to look it up by recordId so there does need to be a way to just wrap an existing ABRecord.  I'm also fine with making an enum out of the recordType like you suggest.  I do agree that it would be better to have SwiftAddressBookPerson/Source/Group extend from SwiftAddressBookRecord since all of them are also records themselves.  You would need a public way to be able to create them though since SwiftAddressBook is typically imported as a module.

**Comment by TAKeanice** [comment]
So let's make the initializer public and create the appropriate subclass instance directly instead of a SwiftAddressBookRecord. The convertTo functions can be replaced by failable casts then (we can also keep them to prevent breaking the existing methods and replace their implementation with a safe cast instead of crating new objects)

**Comment by almilli** [comment]
Apparently you can't construct an alternate object in a constructor in swift. If I add this to an initializer it gives a compile error saying "'nil' is the only return value permitted in an initializer"
```
		if ABRecordGetRecordType(internalRecord) == UInt32(kABSourceType) {
			let source = SwiftAddressBookSource(record: internalRecord)
			return source
		}
```

Instead we can make a factory method on the address book wrapper like the recordWithRecord one I added, but it can check the type and return the appropriate one.  And we'll make the initializers public too so they can be created outside the module.

**Comment by TAKeanice** [comment]
Good point! So a factory method is the only option. But then, let's make the record initializer private, that it is obligatory to use the factory method and create a suitable instance directly, best inside the SwiftAddressBookRecord class! Thanks for your help :)

**Comment by TAKeanice** [comment]
Will you update your pull request to employ the discussed points?

**Comment by almilli** [comment]
Ok, I've made the changes

**Comment by TAKeanice** [comment]
Thanks for your contribution :) One more thing: Please note the contributiors agreement.

**Comment by cristeap** [comment]
Thank your for this great wrapper.

Would any of you gentlemen please provide some sample code to the " README.md" of how to retrieve the the actual "addresses" from the "person". I just can't seem to map it or convert it correctly.

The names, emails, and phone numbers all work great, but I just can't map the "addresses". I've also tried "person.internalRecord"

I've looked at the sample code in "SwiftAddressBookPersonTests.swift" and "TableViewController.swift
" as a guide, but still no luck.
--------------------------------------------------------------
if let people = swiftAddressBook?.allPeople {
            for person in people {
                    var iWantCityName: String =  ???
            }
}
--------------------------------------------------------------
Thank You,
Paul

**Comment by TAKeanice** [comment]
Dear Paul, you commented below a pull request. There are other places to ask such things. Look at the unit test code or the wiki for more extensive examples!

**Pull request merged**
